### ISSUE TITLE
Authentication Exception

### ISSUE THREAD

**Issue by seiz** [keplarllp/google-analytics-export-to-csv#8]
Hello,

since a couple of days, ga2csv can no longet authenticate to google. When i run my scripts, i get the following error:

```
Exception in thread "main" com.google.gdata.util.AuthenticationException: Error authenticating (check service name)
    at com.google.gdata.client.GoogleAuthTokenFactory.getAuthException(GoogleAuthTokenFactory.java:628)
    at com.google.gdata.client.GoogleAuthTokenFactory.getAuthToken(GoogleAuthTokenFactory.java:500)
    at com.google.gdata.client.GoogleAuthTokenFactory.setUserCredentials(GoogleAuthTokenFactory.java:346)
    at com.google.gdata.client.GoogleService.setUserCredentials(GoogleService.java:362)
    at com.google.gdata.client.GoogleService.setUserCredentials(GoogleService.java:317)
    at com.google.gdata.client.GoogleService.setUserCredentials(GoogleService.java:301)
    at co.orderly.ga2csv.GoogleAnalyticsExporter.initAnalytics(GoogleAnalyticsExporter.scala:67)
    at co.orderly.ga2csv.GoogleAnalyticsExporter.<init>(GoogleAnalyticsExporter.scala:43)
    at co.orderly.ga2csv.Ga2CsvMain$.main(MainApplication.scala:50)
    at co.orderly.ga2csv.Ga2CsvMain.main(MainApplication.scala)
```

Is there anything i can do to make it work again?
Is this maybe related to the [ShutDown of ClientLogin](http://googledevelopers.blogspot.ch/2015/02/reminder-clientlogin-shutdown-scheduled.html)? 

Thanks a lot!
Stefan

**Comment by mrmolm3** [comment]
Hi seiz, I have exactly the same problem, when i run my scripts i get the same error, i am searching if could solve it, if you get a solution write me here please.
